"""create condition_values

Revision ID: 51c32db542a4
Revises: afbf1f8074eb
Create Date: 2026-08-30 10:14:28.004268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c32db542a4'
down_revision: Union[str, Sequence[str], None] = 'afbf1f8074eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition_instance_id', sa.Integer(), nullable=False),
    sa.Column('condition_field_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('display_value', sa.Text(), nullable=True),
    sa.Column('value_status', sa.String(length=20), nullable=False),
    sa.Column('value_source', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condition_field_id'], ['condition_fields.id'], ),
    sa.ForeignKeyConstraint(['condition_instance_id'], ['condition_instances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condition_instance_id', 'condition_field_id', name='uq_condition_values_instance_field')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('condition_values')
    # ### end Alembic commands ###
