"""create condition_fields

Revision ID: 9ada57a62a70
Revises: 320d95885310
Create Date: 2026-08-30 09:31:06.526157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ada57a62a70'
down_revision: Union[str, Sequence[str], None] = '320d95885310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('condition_group_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value_type', sa.String(length=30), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condition_group_id'], ['condition_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('condition_group_id', 'code', name='uq_condition_fields_group_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('condition_fields')
    # ### end Alembic commands ###
