"""create condition_instances

Revision ID: afbf1f8074eb
Revises: e5ade427213d
Create Date: 2026-08-30 09:53:48.065848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afbf1f8074eb'
down_revision: Union[str, Sequence[str], None] = 'e5ade427213d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condition_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_revision_id', sa.Integer(), nullable=False),
    sa.Column('condition_group_id', sa.Integer(), nullable=False),
    sa.Column('instance_key', sa.String(length=100), nullable=False),
    sa.Column('instance_name', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['condition_group_id'], ['condition_groups.id'], ),
    sa.ForeignKeyConstraint(['request_revision_id'], ['request_revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_revision_id', 'instance_key', name='uq_condition_instances_revision_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('condition_instances')
    # ### end Alembic commands ###
