"""create analysis_type_conditions

Revision ID: e5ade427213d
Revises: 9ada57a62a70
Create Date: 2026-08-30 09:41:57.881375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5ade427213d'
down_revision: Union[str, Sequence[str], None] = '9ada57a62a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_type_conditions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_type_id', sa.Integer(), nullable=False),
    sa.Column('condition_field_id', sa.Integer(), nullable=False),
    sa.Column('required_level', sa.String(length=30), nullable=False),
    sa.Column('allows_not_applicable', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_type_id'], ['analysis_types.id'], ),
    sa.ForeignKeyConstraint(['condition_field_id'], ['condition_fields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_type_id', 'condition_field_id', name='uq_analysis_type_conditions_type_field')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_type_conditions')
    # ### end Alembic commands ###
